name: Build

on:
  push:
    branches-ignore:
      - master
  pull_request:

jobs:
  build:
    name: Build example docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Should generate USAGE.md for tf11_basic
        uses: ./
        with:
          working-dir: examples/tf11_basic
          template: |
            # Test tf11 basic

            # Usage

            <!--- BEGIN_TF_DOCS --->
            <!--- END_TF_DOCS --->

      - name: Should generate USAGE.md for tf11_extra_args
        uses: ./
        with:
          working-dir: examples/tf11_extra_args
          content-type: document
          indention: 3
          args: --no-sensitive --no-requirements --no-required
          output-method: replace

      - name: Should inject into README.md
        uses: ./
        with:
          working-dir: examples/tf12_basic
          output-file: README.md
          args: ""

      - name: Should generate README.md for tf12_atlantis
        uses: ./
        with:
          atlantis_file: atlantis.yaml
          output-file: README.md
          args: --no-providers

      - name: Should generate README.md for tf12_find and its submodules
        uses: ./
        with:
          find-dir: examples/tf12_find

      - name: Should generate README.md for tf12_inject
        uses: ./
        with:
          find-dir: examples/tf12_inject
          output-file: README.md
          args: --sort-inputs-by-required

      - name: Push up changes
        uses: ./
        with:
          working-dir: examples/tf12_basic
          content-type: json
          output-method: print
          git-push: true
          git-commit-message: "chore: terraform-docs build"
