name: publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/publish.yml
      - Dockerfile
      - action.yml
      - src/docker-entrypoint.sh

env:
  REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker
        uses: docker/login-action@v3
        if: env.REGISTRY_USERNAME != ''
        with:
          registry: quay.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Docker image
        if: env.REGISTRY_USERNAME != ''
        run: |
          docker build --pull --tag quay.io/terraform-docs/gh-actions:edge .
          docker push quay.io/terraform-docs/gh-actions:edge

  release-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
