name: validate

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release-*
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: "."

  readme:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install gomplate
        run: |
          sudo curl -o /usr/local/bin/gomplate -sSL https://github.com/hairyhenderson/gomplate/releases/download/v3.8.0/gomplate_linux-amd64
          sudo chmod 755 /usr/local/bin/gomplate

      - name: Check README content based on action.yml
        if: ${{ github.repository_owner == 'terraform-docs' }}
        run: |
          ./scripts/update-readme.sh
          if [ $(git status --porcelain | grep -c 'M README.md') -eq 1 ]; then
            git diff
            exit 1
          fi

      - name: Check README content based on action.yml
        if: ${{ github.repository_owner != 'terraform-docs' }}
        run: |
          ./scripts/update-readme.sh
          if [ $(git status --porcelain | grep -c 'M README.md') -eq 1 ]; then
            git config user.email "noreply.${{ github.actor }}@github.com"
            git config user.name "${{ github.actor }}"
            git add README.md
            git commit -s -m "docs: README.md Updated"
            git push
          fi
